local builtin = require('telescope.builtin')
pcall(require('telescope').load_extension, 'fzf')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Find files' })
vim.keymap.set('n', '<leader>fs', builtin.live_grep, { desc = 'Search text' })
vim.keymap.set('n', '<leader>fg', builtin.git_files, { desc = 'Find Git files' })
vim.keymap.set('n', '<leader>fh', builtin.oldfiles, { desc = 'Find recent files' })
vim.keymap.set('n', '<leader>fk', builtin.keymaps, { desc = 'Search keymaps' })
vim.keymap.set('n', '<leader>ds', builtin.lsp_document_symbols, { desc = 'LSP: Document symbols' })
vim.keymap.set('n', '<leader>ws', builtin.lsp_workspace_symbols, { desc = 'LSP: Workspace symbols' })
vim.keymap.set('n', '<leader>ci', builtin.lsp_incoming_calls, { desc = 'LSP: Incoming calls' })
vim.keymap.set('n', '<leader>co', builtin.lsp_outgoing_calls, { desc = 'LSP: Outgoing calls' })
